### ISSUE TITLE
Option to have normal movement speed

### ISSUE THREAD

**Issue by MrDj200** [enragedpixel/Carry-Stacker-Reloaded#13]
**Issue:** I'd like an option to have the vanilla movement speed when carrying bags.

**Reason:** For example when I carry 2 Heavy Artifacts, I still move faster than a non modded player with just 1 Heavy Artifact.

**~Crash log:~** N/A

**Mods running:** 
- SuperBLT
- CarryStackerReloaded 
- BeardLib 

**~System information:~** Unrelated

**Comment by m-alorda** [comment]
Hi,

It's been a long time, but I now have some time and might develop a few features for the mod. How would you define "vanilla movement speed"? Say you are carrying four bags:

- A heavy artifact
- A gold bag
- A coke bag
- A money bag

Based on that, how would you define "normal movement speed"?

They way it works now is, movement reductions are stacked. So the total speed reduction would be:
```
speed_reduction = heaver_artifact_reduction * gold_bag_reduction * coke_bag_reduction * money_bag_redution
```
Knowing  this, the desired functionality could probably be achieved by adjusting the current bag penalties (maybe the maximum allowed bag penalty is less than the heavy artifact speed reduction. But that could be changed).

Another way this could work is having speed limited by the heaviest bag. This way, you would move as fast as if you were carrying just one heavy artifact. However, this probably would not make much sense, as you would then move at the exact same speed no matter whether you are holding one artifact or fiveteen.

If you have any other suggestions, I would be happy to hear them :)

**Comment by MrDj200** [comment]
If I remember correctly (Stopped playing Payday 2 a while ago), the way I'd have liked it was to have the penalties increased.
Moving faster with 2 artifacts in your bag than a vanilla player with only 1 artifact feels cheaty

**Comment by m-alorda** [comment]
An option to increase movement penalties have been added in [v1.10.3](https://github.com/enragedpixel/Carry-Stacker-Reloaded/releases/tag/v1.10.3)
