### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Mayzone** [enragedpixel/Carry-Stacker-Reloaded#18]
Issue: Can't access bag table.

Crash log:

Mods running:

System information:

Nevermind, i see there is more versions of this mod. This one doesn't have that problem.

**Comment by m-alorda** [comment]
Hi! I have been working on this mod in [m-alorda/Carry-Stacker-Reloaded](https://github.com/m-alorda/Carry-Stacker-Reloaded). Could you please address the issue and say on which version of the mod did you find it fixed? I would be willing to fix it in the version I am working on

**Comment by Mayzone** [comment]
The one you sent link to does not have an issue but the ones i think you based the mod on, got the issue were bag table is not possible to access globaly. https://pdmods-arc.berigora.net/paydaymods.com/mods/patchnotes/162/5/index.html

https://github.com/Lordmau5/Carry-Stacker-Reloaded/blob/master/Carry%20Stacker%20Reloaded/lua/playermanager.lua

Im not sure if you also have access to these ones but they have the issue

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by m-alorda** [comment]
Oh, I see. The one created by Lordmau5 stopped being maintained a long time ago. Enragedpixel took over afterwards. However, I think he no longer maintains it.

I got into using the mod a couple of months ago, but found some issues, so I decided to go ahead a try to update it myself. If you are willing to use it, you can expect new updates on my repo! :)

**Comment by Mayzone** [comment]
Thanks man. Keep up the good work, sorry to bother you

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by enragedpixel** [comment]
@m-alorda big ups to you, i have been neck deep in some arma modding so i appreciate it, sending an inv to collab here and have merged your req if you want to since this repo is (currently) linked ina few places

**Comment by enragedpixel** [comment]
however if youd like to wholesale take over updating the mod, feel free to go for it, happy to pass the torch

**Comment by Mayzone** [comment]
I would like to be a collaborator for the mod but i haven’t recived any invite.

Fra: enragedpixel<mailto:notifications@github.com>
Sendt: mandag 11. januar 2021 kl. 01.50
Til: enragedpixel/Carry-Stacker-Reloaded<mailto:Carry-Stacker-Reloaded@noreply.github.com>
Kopi: Mayzone<mailto:alben_94@hotmail.com>; Author<mailto:author@noreply.github.com>
Emne: Re: [enragedpixel/Carry-Stacker-Reloaded] Compatibility (#18)


however if youd like to wholesale take over updating the mod, feel free to go for it, happy to pass the torch
