### ISSUE TITLE
mod not showing in options 

### ISSUE THREAD

**Issue by skye1437** [enragedpixel/Carry-Stacker-Reloaded#19]
Issue: i cant seem to find the mod when i download it, I'm putting it in the mods folder 

Crash log:

Mods running:

System information:

**Comment by m-alorda** [comment]
Hi. I'm guessing you've downloaded the master branch as `master.zip` (Either manually or using the download link in README). Have you unzipped it before putting it on the `PAYDAY2/mods` folder?

If you have, could you please be more explicit as to what "finding" the mod means?

**Comment by skye1437** [comment]
Yes I have installed and unzipped the files then placed them into my mods folder but once I load up the game I cannot find the options for the mod anywhere, am I missing a step? Sent from Mail for Windows 10 From: m-alordaSent: January 11, 2021 8:05 AMTo: enragedpixel/Carry-Stacker-ReloadedCc: skye1437; AuthorSubject: Re: [enragedpixel/Carry-Stacker-Reloaded] mod not showing in options (#19) Hi. I'm guessing you've downloaded the master branch as master.zip (Either manually or using the download link in README). Have you unzipped it before putting it on the PAYDAY2/mods folder?If you have, could you please be more explicit as to what "finding" the mod means?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by m-alorda** [comment]
It seems like the steps you are taking are fine.

The mod options should be in `Options -> Mod Options -> Carry Stacker Reloaded`. If they are not present, I'm going to need more information, as I have tried uninstalling and reinstalling the mod, and it works just fine for me.

I need to see your game **logs**. If you do not know how to get them, these are the steps:
- Quit the game (if currently running).
- Create an empty file named `developer.txt` in your `PAYDAY2/mods` folder.
- Start the game (a terminal should show up, and the logs will be printed there).
- Try and find the mod options.
- Quit the game.
- A new folder called `logs` will have been created in the `PAYDAY2/mods` folder. Inside it, there will be a file containing the logs. The contents of this file are what I need.

Also, please provide a **list of all the mods you currently have installed**.

Note: your previous comment was not formatted correctly. Please, try to make sure it is properly formatted so it is easier for me to help you.

**Comment by skye1437** [comment]
Hello, I’m sorry for the late response but it seems the issue was that my 7-zip had suddenly stopped working for some reason. I switched to WinRAR and everything seems to work fine now. Thank you for your help Sent from Mail for Windows 10 From: m-alordaSent: January 11, 2021 9:32 AMTo: enragedpixel/Carry-Stacker-ReloadedCc: skye1437; AuthorSubject: Re: [enragedpixel/Carry-Stacker-Reloaded] mod not showing in options (#19) It seems like the steps you are taking are fine.The mod options should be in Options -> Mod Options -> Carry Stacker Reloaded. If they are not present, I'm going to need more information, as I have tried uninstalling and reinstalling the mod, and it works just fine for me.I need to see your game logs. If you do not know how to get them, these are the steps:Quit the game (if currently running).Create an empty file named developer.txt in your PAYDAY2/mods folder.Start the game (a terminal should show up, and the logs will be printed there).Try and find the mod options.Quit the game.A new folder called logs will have been created in the PAYDAY2/mods folder. Inside it, there will be a file containing the logs. The contents of this file are what I need.Also, please provide a list of all the mods you currently have installed.Note: your previous comment was not formatted correctly. Please, try to make sure it is properly formatted so it is easier for me to help you.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
