### ISSUE TITLE
Doesn't work for other players just host

### ISSUE THREAD

**Issue by geicorules** [enragedpixel/Carry-Stacker-Reloaded#2]
Issue: No matter how many or how few mods my friends and I run only the host is ever granted carry stack. Tried checking and unchecking sync with host.

Crash log:

Mods running: Just this

System information:

**Comment by enragedpixel** [comment]
Do all players have carry stacker and BLT installed correctly?

**Comment by geicorules** [comment]
Yes. If I host it works for me if they host if works for them but never for all players.

**Comment by enragedpixel** [comment]
Is the sync with host option checked?

**Comment by geicorules** [comment]
Currently both myself (the host) as well as my friend has it checked.

**Comment by enragedpixel** [comment]
I'll test it as soon as I can get one more person online and fix it asap

**Comment by geicorules** [comment]
Okay thank you very much and let me know ow if there is anything I can do to help

**Comment by enragedpixel** [comment]
I've added you on steam if you'd like to help test and fix this issue

**Comment by geicorules** [comment]
Cool I have other obligations until around 4-5pst today but would be willing to help out after that.

**Comment by enragedpixel** [comment]
For anyone reading this Issue found: Sydney hud is incompatible, reviewing the issue, if it's on my end I'll attempt to fix, thanks Geico for the testing help
