### ISSUE TITLE
Cannot open the menu

### ISSUE THREAD

**Issue by lxw912** [enragedpixel/Carry-Stacker-Reloaded#22]
Issue:Mod cannot open the menu

Crash log:No carsh log

Mods running:
![QQ截图20210618000137](https://user-images.githubusercontent.com/86013916/122433160-8b281200-cfc8-11eb-9708-964ce4bfc112.png)
![QQ截图20210618000151](https://user-images.githubusercontent.com/86013916/122433169-8cf1d580-cfc8-11eb-9274-19d466108787.png)
![QQ截图20210618000201](https://user-images.githubusercontent.com/86013916/122433171-8d8a6c00-cfc8-11eb-9245-e788f3208328.png)
![QQ截图20210618000207](https://user-images.githubusercontent.com/86013916/122433177-8e230280-cfc8-11eb-810b-a5d3fbe43699.png)

System information:
        Application version : 1.107.18
	CPU : Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 Ti / nvldumd.dll[27.21.14.6677]
	Language : schinese
	Memory :     16304MB 244KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (鎵０鍣?(Realtek(R) Audio))

![payday2_win32_release 2021-06-17 23-58-12](https://user-images.githubusercontent.com/86013916/122433397-c62a4580-cfc8-11eb-8b3f-d54d54a8bc59.png)
![payday2_win32_release 2021-06-17 23-58-01](https://user-images.githubusercontent.com/86013916/122433475-db06d900-cfc8-11eb-8b85-0ae8d1a8a015.png)
![payday2_win32_release 2021-06-17 23-58-05](https://user-images.githubusercontent.com/86013916/122433488-dd693300-cfc8-11eb-9220-9b19a98cdd56.png)

**Comment by m-alorda** [comment]
Hi! I just checked the problem, and I can open the mod's options menu just fine. Both in-game and from the main menu.

From the images you sent it seems like you may be running an older version of the mod. Could you please check you have the  [latest](https://github.com/enragedpixel/Carry-Stacker-Reloaded/releases/latest/download/CarryStackerReloaded.zip) version running?

**Comment by lxw912** [comment]
> Hi! I just checked the problem, and I can open the mod's options menu just fine. Both in-game and from the main menu.
> 
> From the images you sent it seems like you may be running an older version of the mod. Could you please check you have the [latest](https://github.com/enragedpixel/Carry-Stacker-Reloaded/releases/latest/download/CarryStackerReloaded.zip) version running?

Okay, thank you for your help, I will install the new version according to your instructions, thank you again for your time :)

**Comment by m-alorda** [comment]
@lxw912 If that fixes it, please let me know, so I can close the issue. However, if the problem continues, please provide further details on what you are doing.

Also, if you add an empty file named `developer.txt` to your `PAYDAY2/mods` folder, the Lua logs would be created. They would be really useful for fixing this, if you could provide them:
- Create the file
- Open the game
- Do whatever makes the mod not working
- Close the game
- Copy the logs from `PAYDAY2/mods/logs`

**Comment by lxw912** [comment]
> @lxw912如果解决了问题，请告诉我，以便我可以关闭问题。但是，如果问题仍然存在，请提供有关您正在执行的操作的更多详细信息。
> 
> 此外，如果你添加一个名为的空文件`developer.txt`到您的`PAYDAY2/mods`文件夹，将创建的Lua的日志。如果您可以提供它们，它们对于解决此问题非常有用：
> 
> * 创建文件
> * 打开游戏
> * 做任何使 mod 不起作用的事情
> * 关闭游戏
> * 将日志从 `PAYDAY2/mods/logs`

The mod is now able to run, you can close this issue

**Comment by lxw912** [comment]
> @lxw912 If that fixes it, please let me know, so I can close the issue. However, if the problem continues, please provide further details on what you are doing.
> 
> Also, if you add an empty file named `developer.txt` to your `PAYDAY2/mods` folder, the Lua logs would be created. They would be really useful for fixing this, if you could provide them:
> 
> * Create the file
> * Open the game
> * Do whatever makes the mod not working
> * Close the game
> * Copy the logs from `PAYDAY2/mods/logs`

The mod is now able to run, you can close this issue
