### ISSUE TITLE
Does not load on v 216.2

### ISSUE THREAD

**Issue by Necrovoice** [enragedpixel/Carry-Stacker-Reloaded#25]
Issue: Fails to load mod on PD2 version 216.2

Crash log:  N/A

Mods running: SuperBLT, Wolfhud, Silent assassin

System information: Windows 10

**Comment by m-alorda** [comment]
Works fine for me on PD2 version 217.1. What version of the mod are you using? Latest is [v1.10.3](https://github.com/enragedpixel/Carry-Stacker-Reloaded/releases/tag/v1.10.3)

**Comment by Necrovoice** [comment]
Thanks for the reply,  Just checked after the 217.1 update and Carry does not load. Checked with a fresh v1.10.3 download before and after the patch.

In the log files.. I did find this (mod.txt does exist in mods\Carry-Stacker-Reloaded-1.10.3\CarryStackerReloaded)

03:48:24 PM Lua: [INFO] [BLT] Setup... 
03:48:24 PM Lua: [INFO] [BLT] Loading module: BLTLogs 
03:48:24 PM Lua: [INFO] [BLT] Loading module: BLTModManager 
03:48:24 PM Lua: [INFO] [BLT] Loading module: BLTKeybindsManager 
03:48:24 PM Lua: [INFO] [BLT] Loading module: BLTPersistScripts 
03:48:24 PM Lua: [INFO] [BLT] Loading module: BLTLocalization 
03:48:24 PM Lua: [INFO] [BLT] Cleaning logs folder, lifetime 1 day(s) 
03:48:24 PM Lua: [INFO] [BLT] Loading mods for state: table: 0x001f8ca0 
03:48:24 PM Lua: [INFO] [BLT] Loading mod: base 
03:48:24 PM Lua: [INFO] [BLT] Loading mod: Carry-Stacker-Reloaded-1.10.3 
03:48:24 PM Lua: [WARNING] [BLT] Could not read or find mod.txt in Carry-Stacker-Reloaded-1.10.3

**Comment by Necrovoice** [comment]
After finding that in the log file I managed to get it working.
Had to move Subfolder CarryStackerReloaded directly to the mods folder

Before > mods\Carry-Stacker-Reloaded-1.10.3\CarryStackerReloaded
After > mods\CarryStackerReloaded

Forced BLT update manager to think there was an update. Ran that and everything is back to normal. Again thank you for the responce.

**Comment by m-alorda** [comment]
Hi. Yes, currently the mod is not meant to be downloaded straight away from the repo and pasted into the mods folder. You actually need to add the `CarryStackerReloaded` folder. That's why I added a download button: to get the bundle from the latest release.

Sorry I took so long to respond, but I only work on this in my spare time.

Enjoy using the mod again! :)
