### ISSUE TITLE
Is it possible to modify the mod?

### ISSUE THREAD

**Issue by ghost** [enragedpixel/Carry-Stacker-Reloaded#27]
I would like to increase the number of bags I can carry, is it possible?

**Comment by m-alorda** [comment]
Hi!

Yes, you can reduce the bags' weight from the mod's settings. If you set all weights to zero, you can carry an infinite amount of bags.

Also, make sure you are running the [latest version](https://github.com/enragedpixel/Carry-Stacker-Reloaded/releases/latest) of the mod.
