### ISSUE TITLE
question: does this give you cheater tag?

### ISSUE THREAD

**Issue by altacountbabi** [enragedpixel/Carry-Stacker-Reloaded#30]
I dont really wanna get cheater tag and im wondering if you will get it if you use this mod on offline mode

**Comment by m-alorda** [comment]
Hi! I stopped playing PD2 a couple of years ago. So I don't currently know if this mod gives you the cheater tag nowadays.

Still, when I used to use it, it would not give me the cheater tag neither in online nor offline. However, I only used it in stealth heists, not in loud ones.

**Comment by altacountbabi** [comment]
turns out it doesnt, great mod btw
