### ISSUE TITLE
Game crashes when trying to join a lobby

### ISSUE THREAD

**Issue by Dxngoh** [enragedpixel/Carry-Stacker-Reloaded#5]
Application has crashed: C++ exception
mods/Carry Stacker Reloaded/lua/networkhandler.lua:40: attempt to call method 'DisableMod' (a nil value)

SCRIPT STACK

init_finalize() lib/network/base/networkmanager.lua:121
init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.81.426.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960M / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     8081MB 800KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speaker/Headphone (Realtek High Definition Audio))

**Comment by HadesDurin** [comment]
this is my issue report:
Application has crashed: C++ exception
mods/base/req/core/Networking.lua:97: bad argument #2 to 'gsub' (string/function/table expected)



SCRIPT STACK

SendToPeers() @mods/base/req/core/Networking.lua:97
callback() @mods/Carry Stacker Reloaded/lua/configuration_menu.lua:206
trigger() core/lib/managers/menu/items/coremenuitem.lua:150
core/lib/managers/menu/coremenulogic.lua:284
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:772
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

**Comment by theo-ardouin** [comment]
Working on it. Should be fixed soon.

**Comment by enragedpixel** [comment]
fixed as of 11/6/2017, thanks to theo
