### ISSUE TITLE
Crash when "only offline" is selected and joining an online game

### ISSUE THREAD

**Issue by loldev69** [enragedpixel/Carry-Stacker-Reloaded#7]
Issue: game crashes when trying to join an  online game with "only offline" selected

Crash log:
Crash log:Application has crashed: C++ exception
mods/Carry Stacker Reloaded/lua/networkhandler.lua:40: attempt to call method 'DisableMod' (a nil value)

SCRIPT STACK

init_finalize() lib/network/base/networkmanager.lua:121
init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.440.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     8173MB 580KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (S236HL-4 (NVIDIA High Definition Audio))

Mods running: only this one and BLT, disabled the others to test

**Comment by theo-ardouin** [comment]
Are you sure you currently have the _last_ version ?

**Comment by loldev69** [comment]
Sorry, missed last update. I take it that the auto update doesn't work anymore then?

**Comment by theo-ardouin** [comment]
Yep, the auto-update is down for now. :(
